name: "Build CCADB Sqlite 3 Database and CSV"

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '35 3 * */1 *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Generate CCADB Table
        run: $GITHUB_WORKSPACE/ccadb.sh

      - uses: actions/upload-artifact@v3
        with:
          name: cca.db
          path: cca.db

      - uses: actions/upload-artifact@v3
        with:
          name: CCADB.csv
          path: CCADB.csv
