name: "Build CCADB SQLite 3 Database and CSV"

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '35 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Generate CCADB Table
        run: $GITHUB_WORKSPACE/ccadb.sh

      - uses: actions/upload-artifact@v4
        with:
          name: CCADB.db
          path: CCADB.db

      - uses: actions/upload-artifact@v4
        with:
          name: CCADB.csv
          path: CCADB.csv
  commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: CCADB.csv

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          repository: tookmund/CCADB-csv
          path: ccadb-csv
          fetch-depth: 0

      - run: |
          cd ccadb-csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          mv ../CCADB.csv .
          git add CCADB.csv
          git commit -m "Automated CSV Update" || echo "No changes?"
          git push

  # Based on https://github.com/simonw/til
  vercel:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scripts
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          pip3.11 install -r requirements.txt

      - uses: actions/setup-node@v6
        name: Install Node.js
        with:
          node-version: '22.x'

      - name: Install Vercel
        run: |
          npm i -g vercel

      - name: Download CCADB.db
        uses: actions/download-artifact@v5
        with:
          name: CCADB.db

      - name: Deploy Datasette using Vercel
        env:
          NOW_TOKEN: ${{ secrets.VERCEL }}
        run: |-
          datasette publish vercel CCADB.db \
            --project ccadb \
            --metadata metadata.yaml \
            --generate-vercel-json > vercel.json
          sed -i 's/@vercel\/python@3\.0\.7/@vercel\/python@5.0.10/g' vercel.json
          datasette publish vercel CCADB.db \
            --project ccadb \
            --metadata metadata.yaml \
            --vercel-json vercel.json \
            --token $NOW_TOKEN \
            --branch main \
            --public

  commit-scripts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: CCADB.csv

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SCRIPTS_SSH_KEY }}
          repository: tookmund/CCADB-scripts
          path: ccadb-scripts
          fetch-depth: 0

      - run: |
          cd ccadb-scripts
          git switch changelog
          git config user.name github-actions
          git config user.email github-actions@github.com
          date -Iseconds >> CHANGELOG
          sha256sum ../CCADB.csv >> CHANGELOG
          printf "\n\n" >> CHANGELOG
          git add CHANGELOG
          git commit -m "Automated CSV Update Checksum"
          git push
